spring.application.name=admin

# === Server ===
server.port=8081

# === Database ===
spring.datasource.url=jdbc:postgresql://192.168.2.200:5432/wpoms-dev
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver